//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labbtresql
{
    using System;
    using System.Collections.Generic;
    
    public partial class Copy
    {
        public Copy()
        {
            this.Loans = new HashSet<Loan>();
        }
    
        public int CopyID { get; set; }
        public int StatusID { get; set; }
        public int BookID { get; set; }
        public Nullable<decimal> PurchaseCost { get; set; }
        public System.DateTime PurchaseYear { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<Loan> Loans { get; set; }
    }
}
