//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labbtresql
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCustWithBook
    {
        public string Customer { get; set; }
        public string BookTitle { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    }
}
